%%run_MRI_cohort.m
%Runs subject-specific Xe-129 MRI-informed digital-twin simulations for the complete MRI cohort.

clear;
clc;

%%Load participant inputs
data = readtable('input_path_to_csv_here.csv');

nSubjects = height(data);

%%Fixed healthy-model parameters
LungVols_healthy = [0.23 0.237 0.264 0.269];

PulmVol_healthy = 0.065;

CapVols_healthy = [0.25 0.25 0.25 0.25];

th_healthy_vec = [1 1 1 1];
th_healthy = 1;

tRBC_healthy_vec = [0.15 0.15 0.15 0.15];
tRBC_healthy = 0.15;

th_RBC_barrier_healthy = [1 1 1 1];

th_scale_healthy = 1;

%%Allocate output variables
DLCO_sim = zeros(nSubjects,1);
KCO_sim  = zeros(nSubjects,1);

DLCO_healthy = zeros(nSubjects,1);
KCO_healthy  = zeros(nSubjects,1);

DLCO_percent_healthy = zeros(nSubjects,1);
KCO_percent_healthy  = zeros(nSubjects,1);

Va_model = zeros(nSubjects,1);
Va_per_model = zeros(nSubjects,1);

D0_base_subject = zeros(nSubjects,1);

%%Loop through participants
for i = 1:nSubjects

    %%Subject-specific GLI healthy reference values
    DLCO_GLI = data.DLCO_GLI(i);
    RV_GLI   = data.RV_GLI(i);
    TLC_GLI  = data.TLC_GLI(i);
    VA_GLI   = data.VA_GLI(i);

    Va_per_GLI = VA_GLI / TLC_GLI;

    %%Calibrate subject-specific healthy diffusion coefficient
    D0_guess = 0.001;

    [DLCO_guess, ~] = Simulate_KCO( ...
        RV_GLI, TLC_GLI, Va_per_GLI, ...
        LungVols_healthy, ...
        PulmVol_healthy, ...
        CapVols_healthy, ...
        D0_guess, ...
        th_healthy_vec, ...
        th_healthy, ...
        tRBC_healthy_vec, ...
        tRBC_healthy, ...
        th_RBC_barrier_healthy, ...
        th_scale_healthy);

    D0_base_subject(i) = ...
        D0_guess * (DLCO_GLI / DLCO_guess);

    %%Healthy reference simulation
    [DLCO_healthy(i), KCO_healthy(i)] = ...
        Simulate_KCO( ...
        RV_GLI, TLC_GLI, Va_per_GLI, ...
        LungVols_healthy, ...
        PulmVol_healthy, ...
        CapVols_healthy, ...
        D0_base_subject(i), ...
        th_healthy_vec, ...
        th_healthy, ...
        tRBC_healthy_vec, ...
        tRBC_healthy, ...
        th_RBC_barrier_healthy, ...
        th_scale_healthy);

    %%Patient-specific RV and TLC
    RV = RV_GLI * data.RV_percent(i) / 100;
    TLC = TLC_GLI * data.TLC_percent(i) / 100;

    %%Patient-specific regional lung-volume distribution
    LungVols = [ ...
        data.LungVol_1(i), ...
        data.LungVol_2(i), ...
        data.LungVol_3(i), ...
        data.LungVol_4(i)];

    %%Pulmonary blood-volume assumptions
    PulmVol = 0.065;

    CapVols = [0.25 0.25 0.25 0.25];

    %%MRI ventilation-defect scaling
    VDP = data.VDP(i);

    if VDP > 1
        VDP = VDP / 100;
    end

    FRC = data.FRC(i);

    %%Anatomical dead space
    height_cm = data.Height_cm(i);

    Vd = (2.2 * height_cm) / 1000;

    %%Ventilated volume
    VDV = VDP * (FRC + 1);

    VV = (FRC + 1) - Vd - VDV;

    Va = VV;
    Va_per = Va / TLC;

    if Va_per <= 0
        error( ...
            'Participant %d generated Va/TLC <= 0.', i);
    end

    if Va_per > 1
        warning( ...
            'Participant %d generated Va/TLC > 1; capped at 1.', i);

        Va_per = 1;
        Va = TLC;
    end

    Va_model(i) = Va;
    Va_per_model(i) = Va_per;

    %%Xe-129 RBC:barrier scaling
    RBC_barrier_patient = data.RBC_barrier(i);

    RBC_barrier_healthy = ...
        data.RBC_barrier_healthy(i);

    RBC_barrier_relative = ...
        RBC_barrier_patient / RBC_barrier_healthy;

    th_RBC_barrier = ...
        repmat(RBC_barrier_relative, 1, 4);

    th_scale = 1;

    %%Inputs retained by original model function
    th = [1 1 1 1];
    th_healthy = 1;

    tRBC = [0.15 0.15 0.15 0.15];
    tRBC_healthy = 0.15;

    %%Run patient-specific simulation
    [DLCO_sim(i), KCO_sim(i)] = ...
        Simulate_KCO( ...
        RV, TLC, Va_per, ...
        LungVols, ...
        PulmVol, ...
        CapVols, ...
        D0_base_subject(i), ...
        th, ...
        th_healthy, ...
        tRBC, ...
        tRBC_healthy, ...
        th_RBC_barrier, ...
        th_scale);

    %%Express relative to healthy simulation
    DLCO_percent_healthy(i) = ...
        100 * DLCO_sim(i) / DLCO_healthy(i);

    KCO_percent_healthy(i) = ...
        100 * KCO_sim(i) / KCO_healthy(i);

end

%%Save model outputs
results = table( ...
    data.SubjectID, ...
    DLCO_sim, ...
    KCO_sim, ...
    DLCO_healthy, ...
    KCO_healthy, ...
    DLCO_percent_healthy, ...
    KCO_percent_healthy, ...
    Va_model, ...
    Va_per_model, ...
    D0_base_subject);

results.Properties.VariableNames = { ...
    'SubjectID', ...
    'DLCO_simulated', ...
    'KCO_simulated', ...
    'DLCO_healthy_simulation', ...
    'KCO_healthy_simulation', ...
    'DLCO_percent_healthy', ...
    'KCO_percent_healthy', ...
    'Va_model_L', ...
    'Va_TLC_model', ...
    'D0_base_subject'};

writetable(results, ...
    'output_MRI_simulation_results.csv');

disp(results);