%Runs qCT-informed ILD digital-twin simulations for the full cohort.

clear;
clc;

%%Load subject-specific model inputs

data = readtable('ILD_data.csv');

nSubjects = height(data);

%%Healthy/reference model parameters

LungVols_healthy = [0.23 0.237 0.264 0.269];

PulmVol_healthy = 0.065;

CapVols_healthy = [0.25 0.25 0.25 0.25];

th_healthy_value = 1.0;
th_healthy_vec = [1 1 1 1];

SA_scale_healthy = [1 1 1 1];

tRBC_healthy_vec = [0.15 0.15 0.15 0.15];
tRBC_healthy = 0.15;

th_RBC_barrier_healthy = [1 1 1 1];

th_scale = 1;

D0_guess = 0.001;

%%Allocate outputs

DLCO_sim = zeros(nSubjects,1);
KCO_sim  = zeros(nSubjects,1);

DLCO_healthy = zeros(nSubjects,1);
KCO_healthy  = zeros(nSubjects,1);

D0_base_subject = zeros(nSubjects,1);

%%Loop through participants

for i = 1:nSubjects

    %%Subject-specific GLI reference values

    DLCO_GLI = data.DLCO_GLI(i);

    RV_GLI  = data.RV_GLI(i);
    TLC_GLI = data.TLC_GLI(i);
    VA_GLI  = data.VA_GLI(i);

    Va_per_GLI = VA_GLI / TLC_GLI;

    %%Calibrate subject-specific D0_base

    [DLCO_healthy_guess, ~] = ...
        Simulate_KCO_qCT( ...
            RV_GLI, TLC_GLI, Va_per_GLI, ...
            LungVols_healthy, ...
            PulmVol_healthy, ...
            CapVols_healthy, ...
            D0_guess, ...
            th_healthy_vec, ...
            th_healthy_value, ...
            tRBC_healthy_vec, ...
            tRBC_healthy, ...
            th_RBC_barrier_healthy, ...
            th_scale, ...
            SA_scale_healthy);

    D0_base_subject(i) = ...
        D0_guess * ...
        (DLCO_GLI / DLCO_healthy_guess);

    %%Re-run calibrated healthy simulation

    [DLCO_healthy(i), KCO_healthy(i)] = ...
        Simulate_KCO_qCT( ...
            RV_GLI, TLC_GLI, Va_per_GLI, ...
            LungVols_healthy, ...
            PulmVol_healthy, ...
            CapVols_healthy, ...
            D0_base_subject(i), ...
            th_healthy_vec, ...
            th_healthy_value, ...
            tRBC_healthy_vec, ...
            tRBC_healthy, ...
            th_RBC_barrier_healthy, ...
            th_scale, ...
            SA_scale_healthy);

    %%Patient-specific qCT inputs

    RV = data.RV(i);
    TLC = data.TLC(i);
    Va_per = data.Va_TLC(i);

    LungVols = [ ...
        data.LungVol_1(i), ...
        data.LungVol_2(i), ...
        data.LungVol_3(i), ...
        data.LungVol_4(i)];

    PulmVol = data.PulmVol(i);

    CapVols = [ ...
        data.CapVol_1(i), ...
        data.CapVol_2(i), ...
        data.CapVol_3(i), ...
        data.CapVol_4(i)];

    th = [ ...
        data.ACM_1(i), ...
        data.ACM_2(i), ...
        data.ACM_3(i), ...
        data.ACM_4(i)];

    SA_scale = data.SA_scale(i);

    %%Run qCT-informed patient simulation

    [DLCO_sim(i), KCO_sim(i)] = ...
        Simulate_KCO_qCT( ...
            RV, TLC, Va_per, ...
            LungVols, ...
            PulmVol, ...
            CapVols, ...
            D0_base_subject(i), ...
            th, ...
            th_healthy_value, ...
            tRBC_healthy_vec, ...
            tRBC_healthy, ...
            th_RBC_barrier_healthy, ...
            th_scale, ...
            SA_scale);

end

%%Save results

results = table( ...
    data.SubjectID, ...
    DLCO_sim, ...
    KCO_sim, ...
    DLCO_healthy, ...
    KCO_healthy, ...
    D0_base_subject);

results.Properties.VariableNames = { ...
    'SubjectID', ...
    'DLCO_simulated', ...
    'KCO_simulated', ...
    'DLCO_healthy_simulation', ...
    'KCO_healthy_simulation', ...
    'D0_base_subject'};

writetable( ...
    results, ...
    'output/ILD_simulation_results.csv');

disp(results);